### ISSUE TITLE
xfdf. Cyrillic letters are not visible in pdf form.

### ISSUE THREAD

**Issue by Pavlentio** [ruby-journal/nguyen#3]
when I fill pdf form via xfdf with cyrillic letters, it not visible in pdf form while I  don't make field active.

**Comment by Pavlentio** [comment]
it's problem of the pdftk app, maybe it will be solved in short future.

**Comment by joneslee85** [comment]
@Pavlentio thanks for the reporting, because it is not related to this gem, I'll close it now
